### ISSUE TITLE
Visual builder disable issue

### ISSUE THREAD

**Issue by shivam201312** [oracle/vbcs-samples#3]
I am working on a mobile app . i have to create a drop down list (Select One) . i have to disable first option when user click on list . Suppose drop down contains following options
1) Please Select Value
2) Value 1
3) Value 2
so when user click/tap on the drop down above value should appear to the user ."Please Select Value" Option should be disabled . user cannot select it . Other option like Value 1 and Value 2 user can select  it.
I have tried to disable value of "Please Select Value" Option .For some drop down it is working but not for all. 
while development when i  run Mobile App in Web Browser then sometimes it shows "Please Select Value " option disabled but when i build APK of the same code and install it on my device then "Please Select Value "  is not disabled .
How can i find reason why list options are not disabling ?

**Comment by dkonecny-oracle** [comment]
This is Oracle JET specific question. Have a look at their recipe how to disable individual select-one items at https://www.oracle.com/webfolder/technetwork/jet-710/jetCookbook.html?component=selectOne&demo=disabled
And if that does not help please repost your question on JET forum at https://community.oracle.com/community/groundbreakers/development_tools/oracle-jet
