### ISSUE TITLE
ApplicationsCloudUI for vbcs 2104

### ISSUE THREAD

**Issue by ghost** [oracle/vbcs-samples#7]
Hi, we are using vbcs 2104 version with JET 9.2 and we are receiving console logs like this

Your CSS file is compatible with JET version undefined, but you are using JET version 9.2.6.
    Please update your CSS to match the version of JET being used.

We are using ApplicationsCloudUI version 4.0.0

**Comment by bfrybfry** [comment]
Thank you for reporting. We have posted a new version of the JET theme (4.1.0) which is compatible with JET 9.2
